format = """
$os\
$username\
[](bg:color_sky fg:color_silver)\
$directory\
[](fg:color_sky bg:color_violet)\
$git_branch\
$git_status\
[](fg:color_violet bg:color_steel)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_steel bg:color_storm)\
$docker_context\
$conda\
[](fg:color_storm bg:color_night)\
$time\
[ ](fg:color_night)\
$line_break$character"""

palette = 'tokyo_night'

[palettes.tokyo_night]
color_fg0 = '#090c0c'
color_fg1 = '#e3e5e5'
color_fg2 = '#769ff0'
color_fg3 = '#a0a9cb'
color_silver = '#c0caf5'
color_sky = '#7aa2f7'
color_violet = '#9d7cd8'
color_steel = '#414868'
color_storm = '#24283b'
color_night = '#1a1b26'

[os]
disabled = false
style = "bg:color_silver fg:color_fg0"
format = '[ $symbol]($style)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_silver fg:color_fg0"
style_root = "bg:color_silver fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg1 bg:color_sky"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_violet"
format = '[[ $symbol $branch ](fg:color_fg1 bg:color_violet)]($style)'

[git_status]
style = "bg:color_violet"
format = '[[($all_status$ahead_behind )](fg:color_fg1 bg:color_violet)]($style)'

[nodejs]
symbol = ""
style = "bg:color_steel"
format = '[[ $symbol( $version) ](fg:color_fg2 bg:color_steel)]($style)'

[c]
symbol = " "
style = "bg:color_steel"
format = '[[ $symbol( $version) ](fg:color_fg2 bg:color_steel)]($style)'

[rust]
symbol = ""
style = "bg:color_steel"
format = '[[ $symbol( $version) ](fg:color_fg2 bg:color_steel)]($style)'

[golang]
symbol = ""
style = "bg:color_steel"
format = '[[ $symbol( $version) ](fg:color_fg2 bg:color_steel)]($style)'

[php]
symbol = ""
style = "bg:color_steel"
format = '[[ $symbol( $version) ](fg:color_fg2 bg:color_steel)]($style)'

[java]
symbol = ""
style = "bg:color_steel"
format = '[[ $symbol( $version) ](fg:color_fg2 bg:color_steel)]($style)'

[kotlin]
symbol = ""
style = "bg:color_steel"
format = '[[ $symbol( $version) ](fg:color_fg2 bg:color_steel)]($style)'

[haskell]
symbol = ""
style = "bg:color_steel"
format = '[[ $symbol( $version) ](fg:color_fg2 bg:color_steel)]($style)'

[python]
symbol = ""
style = "bg:color_steel"
format = '[[ $symbol( $version) ](fg:color_fg2 bg:color_steel)]($style)'

[docker_context]
symbol = ""
style = "bg:color_storm"
format = '[[ $symbol( $context) ](fg:color_fg2 bg:color_storm)]($style)'

[conda]
style = "bg:color_storm"
format = '[[ $symbol( $environment) ](fg:color_fg2 bg:color_storm)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_night"
format = '[[  $time ](fg:color_fg3 bg:color_night)]($style)'

[line_break]
disabled = false

[character]
disabled = false
