format = """
$os\
$username\
[](bg:color_bg1 fg:color_bg0)\
$directory\
[](fg:color_bg1 bg:color_bg2)\
$git_branch\
$git_status\
[](fg:color_bg2 bg:color_bg3)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_bg3 bg:color_bg4)\
$docker_context\
$conda\
[](fg:color_bg4 bg:color_bg5)\
$time\
[ ](fg:color_bg5)\
$line_break$character"""

palette = 'pastel'

[palettes.pastel]
color_fg0 = '#FFFFFF'
color_fg1 = '#FFFFFF'
color_fg2 = '#FFFFFF'
color_fg3 = '#FFFFFF'
color_bg0 = '#9A348E'
color_bg1 = '#DA627D'
color_bg2 = '#FCA17D'
color_bg3 = '#86BBD8'
color_bg4 = '#06969A'
color_bg5 = '#33658A'

[os]
disabled = false
style = "bg:color_bg0 fg:color_fg0"
format = '[ $symbol]($style)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_bg0 fg:color_fg0"
style_root = "bg:color_bg0 fg:color_fg0"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg1 bg:color_bg1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_bg2"
format = '[[ $symbol $branch ](fg:color_fg1 bg:color_bg2)]($style)'

[git_status]
style = "bg:color_bg2"
format = '[[($all_status$ahead_behind )](fg:color_fg1 bg:color_bg2)]($style)'

[nodejs]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg2 bg:color_bg3)]($style)'

[c]
symbol = " "
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg2 bg:color_bg3)]($style)'

[rust]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg2 bg:color_bg3)]($style)'

[golang]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg2 bg:color_bg3)]($style)'

[php]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg2 bg:color_bg3)]($style)'

[java]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg2 bg:color_bg3)]($style)'

[kotlin]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg2 bg:color_bg3)]($style)'

[haskell]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg2 bg:color_bg3)]($style)'

[python]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $version) ](fg:color_fg2 bg:color_bg3)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg4"
format = '[[ $symbol( $context) ](fg:color_fg2 bg:color_bg4)]($style)'

[conda]
style = "bg:color_bg4"
format = '[[ $symbol( $environment) ](fg:color_fg2 bg:color_bg4)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg5"
format = '[[  $time ](fg:color_fg3 bg:color_bg5)]($style)'

[line_break]
disabled = false

[character]
disabled = false
